// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2noJ-VqOSHe2ImzY8AnjrNbRN1Cv_Ekw',
    appId: '1:35752828261:web:a7a0b5ce1336c8ed4b958c',
    messagingSenderId: '35752828261',
    projectId: 'surveysproutapp-20251008153124',
    authDomain: 'surveysproutapp-20251008153124.firebaseapp.com',
    storageBucket: 'surveysproutapp-20251008153124.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk8OwANivoJBiLB-LweSCzJIpfopFn1_M',
    appId: '1:35752828261:android:8c25fcac15ce7ce04b958c',
    messagingSenderId: '35752828261',
    projectId: 'surveysproutapp-20251008153124',
    storageBucket: 'surveysproutapp-20251008153124.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwe3I4R7aB6zQhmHpaM2QKFjfllPhnHtg',
    appId: '1:35752828261:ios:4cab25c0027ae6424b958c',
    messagingSenderId: '35752828261',
    projectId: 'surveysproutapp-20251008153124',
    storageBucket: 'surveysproutapp-20251008153124.firebasestorage.app',
    iosBundleId: 'com.example.surveysproutapp',
  );
}
